sudo: required

services:
  - docker

before-install:
  - docker build -t killer1987v/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true killer1987v/docker-react npm run test -- --coverage

deploy:
  provider: elastickbeanstalk
  region: "us-east-2"
  app: "Docker-react1"
  env: "DockerReact1-env"
  bucket_name: "elasticbeanstalk-us-east-2-023868447130"
  bucket_path: "Docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY