sudo: required

services:
  - docker

before-install:
  - docker build -t killer1987v/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true killer1987v/docker-react npm run test -- --coverage