version: "3"
services: 
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: "true"
    ports: 
      - "8000:3000"
      - "6001:3000"
    volumes: 
      - "/usr/app/node_modules"
      - "./:/usr/app/"
  
  react-app-test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: "true"
    volumes: 
      - "/usr/app/node_modules"
      - "./:/usr/app/"
    command: ["npm","run","test"]